"""Creación modelo base

Revision ID: 29c718c95a5e
Revises: 
Create Date: 2025-09-15 19:52:29.897502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29c718c95a5e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('agent_prompt', sa.Text(), nullable=False),
    sa.Column('agent_description', sa.Text(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=False),
    sa.Column('active_agent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_table('maestro_prompts',
    sa.Column('prompt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt_internal_name', sa.String(length=255), nullable=True),
    sa.Column('prompt_description', sa.Text(), nullable=True),
    sa.Column('prompt_content', sa.Text(), nullable=False),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('prompt_id'),
    sa.UniqueConstraint('prompt_internal_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestro_prompts')
    op.drop_table('agents')
    # ### end Alembic commands ###
